
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: sistema_financeiro
      POSTGRES_USER: sistema_financeiro_user
      POSTGRES_PASSWORD: wUxNCzoOZF8BaPqvTZstLJLRSEqkFPaz
    volumes:
      - db-data:/var/lib/postgresql/data  # Adiciona persistência
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - metabase-data:/metabase-data  # Adiciona persistência

volumes:
  db-data:   # Volume para o banco de dados
  metabase-data:  # Volume para o Metabase